web/router.ex
defmodule PhoenixCommerce.Router do
  use PhoenixCommerce.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", PhoenixCommerce do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/products", ProductController
    get "/cart", CartController, :show
    post "/cart/add", CartController, :add, as: :add_to_cart
    resources "/line_items", LineItemController
  end

  # Other scopes may use custom stacks.
  # scope "/api", PhoenixCommerce do
  #   pipe_through :api
  # end
end

web/models/cart.ex
defmodule PhoenixCommerce.Cart do
  use PhoenixCommerce.Web, :model

  schema "carts" do
    field :uuid, Ecto.UUID, autogenerate: true
    has_many :line_items, PhoenixCommerce.LineItem

    timestamps
  end

  @required_fields ~w()
  @optional_fields ~w()

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
  end
end

web/controllers/cart_controller.ex
defmodule PhoenixCommerce.CartController do
  use PhoenixCommerce.Web, :controller

  alias PhoenixCommerce.LineItem
  alias PhoenixCommerce.Cart

  plug :add_cart

  def show(conn, _params) do
    query =
      from li in LineItem,
      where: li.cart_id == ^conn.assigns[:cart].id,
      preload: [:product]

    line_items = Repo.all(query)

    render conn, "show.html", %{line_items: line_items}
  end

  def add(conn, %{"product" => %{"id" => product_id}}) do
    LineItem.changeset(%LineItem{}, %{
      product_id: product_id,
      quantity: 1,
      cart_id: conn.assigns[:cart].id
    }) |> Repo.insert!

    redirect conn, to: cart_path(conn, :show)
  end

  def add_cart(conn, _opts) do
    cart = case get_session(conn, :cart_uuid) do
      nil ->
        Repo.insert!(%Cart{})
      cart_uuid ->
        query =
          from c in Cart,
          where: c.uuid == ^cart_uuid
        Repo.one(query)
    end

    conn
    |> assign(:cart, cart)
    |> put_session(:cart_uuid, cart.uuid)
  end
end

web/views/cart_view.ex
defmodule PhoenixCommerce.CartView do
  use PhoenixCommerce.Web, :view
end

web/templates/cart/show.html.eex
<h2>Your cart</h2>
<div class="cart">
  <table>
    <thead>
      <tr>
        <th>Product</th>
        <th>Quantity</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <%= for line_item <- @line_items do %>
        <tr class="product-<%= line_item.product_id %>">
          <td><%= line_item.product.name %></td>
          <td><%= line_item.quantity %></td>
          <td>
            <%= link "Remove from cart", to: line_item_path(@conn, :delete, line_item), method: :delete, class: "remove-from-cart" %>
            <%= form_for PhoenixCommerce.LineItem.changeset(line_item), line_item_path(@conn, :update, line_item), fn f -> %>
              <%= number_input f, :quantity, class: "quantity" %>
              <%= submit("Update") %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>