web/router.ex
defmodule PhoenixCommerce.Router do
  use PhoenixCommerce.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", PhoenixCommerce do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/products", ProductController
    get "/cart", CartController, :show
    post "/cart/add", CartController, :add, as: :add_to_cart
    resources "/line_items", LineItemController
  end

  # Other scopes may use custom stacks.
  # scope "/api", PhoenixCommerce do
  #   pipe_through :api
  # end
end

web/models/product.ex
defmodule PhoenixCommerce.Product do
  use PhoenixCommerce.Web, :model
  use Arc.Ecto.Model

  schema "products" do
    field :name, :string
    field :description, :string
    field :price, :decimal
    field :image, PhoenixCommerce.Image.Type
    has_many :line_items, PhoenixCommerce.LineItem

    timestamps
  end

  @required_fields ~w(name description price)
  @optional_fields ~w()

  @required_file_fields ~w()
  @optional_file_fields ~w(image)

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
    |> cast_attachments(params, @required_file_fields, @optional_file_fields)
  end
end

web/controllers/product_controller.ex
defmodule PhoenixCommerce.ProductController do
  use PhoenixCommerce.Web, :controller

  alias PhoenixCommerce.Product

  plug :scrub_params, "product" when action in [:create, :update]

  def index(conn, _params) do
    products = Repo.all(Product)
    render(conn, "index.html", products: products)
  end

  def new(conn, _params) do
    changeset = Product.changeset(%Product{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"product" => product_params}) do
    changeset = Product.changeset(%Product{}, product_params)

    case Repo.insert(changeset) do
      {:ok, _product} ->
        conn
        |> put_flash(:info, "Product created successfully.")
        |> redirect(to: product_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    product = Repo.get!(Product, id)
    render(conn, "show.html", product: product)
  end

  def edit(conn, %{"id" => id}) do
    product = Repo.get!(Product, id)
    changeset = Product.changeset(product)
    render(conn, "edit.html", product: product, changeset: changeset)
  end

  def update(conn, %{"id" => id, "product" => product_params}) do
    product = Repo.get!(Product, id)
    changeset = Product.changeset(product, product_params)

    case Repo.update(changeset) do
      {:ok, product} ->
        conn
        |> put_flash(:info, "Product updated successfully.")
        |> redirect(to: product_path(conn, :show, product))
      {:error, changeset} ->
        render(conn, "edit.html", product: product, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    product = Repo.get!(Product, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(product)

    conn
    |> put_flash(:info, "Product deleted successfully.")
    |> redirect(to: product_path(conn, :index))
  end
end

web/views/product_view.ex
defmodule PhoenixCommerce.ProductView do
  use PhoenixCommerce.Web, :view
end

web/templates/product/edit.html.eex
<h2>Edit product</h2>

<%= render "form.html", changeset: @changeset,
                        action: product_path(@conn, :update, @product) %>

<%= link "Back", to: product_path(@conn, :index) %>

web/templates/product/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= label f, :description, class: "control-label" %>
    <%= textarea f, :description, class: "form-control" %>
    <%= error_tag f, :description %>
  </div>

  <div class="form-group">
    <%= label f, :price, class: "control-label" %>
    <%= number_input f, :price, step: "any", class: "form-control" %>
    <%= error_tag f, :price %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/product/index.html.eex
<h2>Listing products</h2>

<ul class="products">
  <%= for product <- @products do %>
    <li>
      <h3><%= link product.name, to: product_path(@conn, :show, product.id) %></h3>
      <h4>$<%= product.price %></h4>
      <img src="<%= PhoenixCommerce.Image.url({product.image, product}, :thumb) %>" />
      <p><%= product.description %></p>
    </li>
  <% end %>
</ul>

web/templates/product/new.html.eex
<h2>New product</h2>

<%= render "form.html", changeset: @changeset,
                        action: product_path(@conn, :create) %>

<%= link "Back", to: product_path(@conn, :index) %>

web/templates/product/show.html.eex
<h2>Show product</h2>

<ul>

  <li>
    <strong>Name:</strong>
    <%= @product.name %>
  </li>

  <li>
    <strong>Description:</strong>
    <%= @product.description %>
  </li>

  <li>
    <strong>Price:</strong>
    <%= @product.price %>
  </li>

</ul>

<%= form_for @conn, add_to_cart_path(@conn, :add), [as: "add_to_cart"], fn f -> %>
  <%= hidden_input(:product, :id, value: @product.id) %>
  <%= submit "Add to cart", class: "add-to-cart" %>
<% end %>

<%= link "Edit", to: product_path(@conn, :edit, @product) %>
<%= link "Back", to: product_path(@conn, :index) %>